<script src="http://code.jquery.com/jquery-1.8.0.min.js"></script>
<script src="http://malsup.github.com/jquery.form.js"></script>
<style type="text/css">
	td
	{
		margin-left:100cm;
		padding:10px;
		vertical-align:left;
	}
	.datafeeder-form input[type="text"] {
		width: 300px;
	}
</style>
<script type="text/javascript">
        var $jq = jQuery.noConflict();
</script>
<frameset cols="50%,50%">
	<frame name="actual_frame">	
		<div class="datafeeder-form" onload="allset()">
			<form action="<?php echo $this->getSaveApiUrl();?>" method="POST" >

				<span><b>Unbxd API Key: </b><span>
				<input type="text" name="apikey" style="margin-left: 10px;" value="<?php echo $this->getApiKey(); ?>">
				<input type="submit" style="margin-left: 10px;" value="SAVE"/>
			</form>
            <form action="<?php echo $this->saveFeedConf();?>" method="POST" >
				<p class="switcher">
            	<label for="store_switcher"><b>Choose Store View: </b><label>

                <select id="site" class="site" name="site" onload="newajaxcall('<?php echo $this->getFeedConf(); ?>')" onchange="newajaxcall('<?php echo $this->getFeedConf();?>')">
                    <?php $allsites=Mage::app()->getWebsites();?>
                    <?php foreach ($allsites as $site):?>
                        <option value="<?php echo $site->getName()?>"><?php echo $site->getName()?></option>
					<?php endforeach;?>
				</select>
       			</p>


				<table class="form-list" onload="allset()" id="form-list" name="form-list" cellspacing="0" style="background:none repeat scroll 0 0 #FAFAFA;border=1px solid #D6D6D6;width: 100%;" width="5000px">
				<div class="datafeeder-form" width="parent" style="background:none repeat scroll 0 0 #6F8992;padding:5px 10px; color: white;">
					FEED CONFIGURATION
				</div>
				<tr>
					<td class="label">
						<b>Unbxd Site Name: </b>
					</td>
					<td class="value">				
						<input type="text" id="feedName" name="feedName" value="" disabled/>
					</td>
					</tr>
				</tr>
				<tr>
					<td class="label">
						<b>Unbxd Site Key: </b>
					</td>
					<td class="value">				
						<input type="text" id="siteName" name="siteName" value="" disabled/>
					</td>
					</tr>
				</tr>
				<tr>
					<td class="label">
					</td>
					<td class="value">
						<input type="button" name="editButton" value="EDIT"/> <input style="margin-left: 10px;" type="submit" value="SAVE"/>
					</td>
				</tr>
		</table>	
		
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
		</form>
		<script type="text/javascript">
	
		$jq('[name=editButton]').click(function(evt){
			$jq('[name="feedName"]').attr('disabled', false);
			$jq('[name="siteName"]').attr('disabled', false);
		});

		function progressbar()
		{
			$jq.ajax({
				  //async:false,
				  url: "<?php echo $this->getProgressUrl(); ?>",
				  type:"POST",
				  dataType:"json",
				  data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
					"site": $jq('[name=site]').val()
					},
				  success: function(data) {
					  document.getElementById("ProgressBar").innerHTML="";
					  if(data.status=="0"){
					  	document.getElementById("ProgressBar").innerHTML="<b>Status: Indexed</b>";
					  	document.getElementById("fullupload").disabled=false;
					  }else if(data.status=="1"){
					  	document.getElementById("ProgressBar").innerHTML="<b>Status: Indexing</b>";
					  	document.getElementById("fullupload").disabled=true;
					  }
				  }
				});
			
		}
	
		function callSetInterval()
		{
			setInterval(progressbar,20000);	
		}
			
		function newajaxcall(ajaxurl){
				//createTable('<?php echo $this->getEditUrl();?>');
		  		$jq.ajax({
					  
					  	url: ajaxurl,
					  	timeout:3000,
					  	type:"POST",
						dataType: "json",
					  	data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
						"site":$jq('[name=site]').val(),
					},

					success: function(data) {
				
						if(data.feed !== "empty") $jq('[name=feedName]').val(data.feed); else $jq('[name=feedName]').val("");
						if(data.feed !== "empty") $jq('[name=siteName]').val(data.siteName); else $jq('[name=siteName]').val("");
						

					},
					  
					fail: function(XMLHttpRequest, textStatus, errorThrown) {
					}	  
				});
			}
		
			newajaxcall("<?php echo $this->getFeedConf();?>");
		
			function makeajaxcall(ajaxurl){
		  
		    	$jq.ajax({
					
					url: ajaxurl,
					timeout:100000,
					type:"POST",
					data:{"form_key":"<?php  echo Mage::getSingleton('core/session')->getFormKey()?>",
						"site": $jq('[name=site]').val()
					},

					complete: function(xhr, statusText){	 
					},

					done: function(data) {
				        console.log(data);
					},
				
					fail: function(XMLHttpRequest, textStatus, errorThrown) {
					}	
				});
			}

			setInterval(progressbar,10000);
		</script>
      
		
		<table class="form-list" width="parent" id="form-list" name="form-list" cellspacing="0" style="background:none repeat scroll 0 0 #FAFAFA;border=1px solid #D6D6D6;width: 100%;">
		 <div class="datafeeder-form" width="parent" style="background:none repeat scroll 0 0 #6F8992;padding:5px 10px;color: white;">
		     <div class="refreshDiv" style="float: right;"><span id="ProgressBar"></span><input type="button" id="refresh" onclick="progressbar()" value="REFRESH" style="margin-left: 10px;vertical-align: top;"></div>
				  <b>UPLOAD &amp; INDEX (manual)</b>
                </div>

			<tr>	
				<td class="label"><b>TAXONOMY UPLOAD:  </b></td>
				<td class="value"><input type="button" id="taxonomyupload" onclick="makeajaxcall('<?php echo $this->getTaxonomyUploadFormAction(); ?>')"  value="START"/></td>			
			</tr>

					  
			<tr>						
				<td class="label"><b>PRODUCT FEED UPLOAD:  </b></td>
				<td class="value"><input type="button" id="fullupload" onclick="makeajaxcall('<?php echo $this->getFullIndexFormAction(); ?>')"  value="START"/></td>			
			
			</tr>	  
		    
	</table>
		
		<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>"/>
	</div>
  </frame>
  <frame name="login_frame"></frame>
</frameset>

<!-- FIELD CONFIGURATION -->
<script type="text/javascript">
 	$jq('#config_edit_form').ready(function(){
		createTable('<?php echo $this->getEditUrl();?>');
    });

	function formSubmit()
	{
		$jq('[name=site_name]').val($jq('[name=site]').val());
	 $jq('#config_edit_form').ajaxSubmit(); 
	}

	function createTable(ajaxurl)
	{
		site= $jq("#site").val();
		$jq.ajax({
			url: ajaxurl,
		  	type:"POST",
		  	data:{"site":site},
		}).done( function(data) {
			jarray = $jq.parseJSON(data);
			tableString="<tbody>";
			$jq("#field-list").find("tr").remove(); 
			$jq.each(jarray, function(key, value) {
					tableString+='<tr><td class="label">'+key+"</td>"+'<td class="value">'+'<select  name="'+key+'">'+"<option";
					if(value=="0"){
						tableString+=' selected="selected"';
					}
					tableString+=' value="0">Disabled</option><option';
					if(value!="0"){
                        tableString+=' selected="selected"';
                    }
				  	tableString+=' value="1">Enabled</option></select></td>';
					tableString+='<td class="scope-label"></td><td class=""></td></tr>' 	
			  });
			tableString+="</tbody>";
			$jq('#field-list').append(tableString)
		  });	
}
</script>

<div class="editconfig">
		<div class="content-header">
			<table cellspacing="0">
				<tr>
					<td>
						<h3 <?php if($this->getHeaderCss()): ?>
							class="<?php echo $this->getHeaderCss()?>" <?php endif; ?>>
							<?php echo Mage::helper('adminhtml')->__("FIELD CONFIGURATION") ?>
						</h3>
					</td>
					<td class="form-buttons">
						<input  type="button" style='background:url("images/btn_bg.gif") repeat-x scroll 0 100% #FFAC47;border-color:#ED6502 #A04300 #A04300 #ED6502;border-style:solid;border-width:1px;color:#FFFFFF;font:bold 12px arial,helvetica,sans-serif;text-align:center !important;white-space:nowrap;padding: 3px;' onclick="formSubmit()" value="SAVE"/>
					</td>
				</tr>
			</table>
		</div>
	    <div class="unbxd_edit_config" style="background:none repeat scroll 0 0 #FAFAFA;border:1px solid #D6D6D6">
		
			<form action="<?php echo $this->getSaveFieldUrl() ?>" method="post"
				id="config_edit_form" onload="createTable('<?php echo $this->getEditUrl();?>')">
				<input name="site_name" id= "site_name" type="hidden" />
					<!--<center>-->
				<p class="switcher">		
					<label for="store_switcher"><b> Field Configuration </b><label>
				</p>
				
				<table class="form-list" id="field-list" name="form-list" cellspacing="0" style="color: #2F2F2F;
			    font: 12px/1.5em Arial,Helvetica,sans-serif; margin-left: 10%;">
				</table>
				
				 <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />

			</form>
	    </div>
	</div>
