<!-- AUTOSUGGEST CONFIG -->
<?php
$website = Mage::app()->getWebsite();
$config = Mage::helper('unbxd_search')->getEngineConfigData('autosuggest');
$siteKey = "";
$apiKey = "";
try {
    $siteKey = Mage::helper('unbxd_search')->getSiteName();
    $apiKey = Mage::helper('unbxd_search')->getApiKey();
} catch(Exception $e) {
    //ignoring the exception
}
$isAutosuggestActive = !is_null($siteKey) && !is_null($apiKey)
    && Mage::helper('unbxd_searchcore')->isConfigTrue($website,
        Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_STATUS);
if($isAutosuggestActive) {
    $templateConfig = $this->getTemplateConfig($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_TEMPLATE]); 
    $config = array_merge($config, $templateConfig);
    $autosuggestComponents = $this->getAvailableAutosuggestComp();
    $mainTempateConf = array_values(array_intersect($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_MAIN_TEMPLATE], $autosuggestComponents));
    $sideTemplateConf = array_values(array_intersect($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGET_SIDE_TEMPLATE], $autosuggestComponents));
    $priceField = Mage::getSingleton('unbxd_searchcore/field')->getPriceFieldName();
    $imageField = "imageUrl";
    $productUrlField = Mage::getSingleton('unbxd_searchcore/field')->getProductUrlFieldName();
    $categoryField = Mage::getSingleton('unbxd_searchcore/field')->getCategoryFieldName();
    $brandField = Mage::getSingleton('unbxd_searchcore/field')->getBrandFieldName();
    $titleField = Mage::getSingleton('unbxd_searchcore/field')->getTitleFieldName();
    ?>  
    <link rel="stylesheet" href="//d21gpk1vhmjuf5.cloudfront.net/jquery-unbxdautosuggest.css">
    <script type="text/javascript"
            src="//cdnjs.cloudflare.com/ajax/libs/handlebars.js/2.0.0/handlebars.min.js"></script>
    <script src="//d21gpk1vhmjuf5.cloudfront.net/jquery-unbxdautosuggest.js"></script>
    <script type="text/javascript">
        unbxdAutoSuggestFunction(jQuery, Handlebars);
        var config = {
            "siteName": "<?php echo $siteKey; ?>",
            "APIKey": "<?php echo $apiKey; ?>",
            "resultsClass": "unbxd-as-wrapper",
            "minChars": 1,
            "delay": 100,
            "loadingClass": "unbxd-as-loading",
            "mainWidth": 0,
            "sideWidth": 180,
            "zIndex": 100,
            "position": "absolute",
            "sideContentOn": "<?php echo (in_array($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SIDECONTENT],
            Unbxd_Searchcore_Helper_Constants::$AUTOSUGGEST_SIDECONTENTS))?
            $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SIDECONTENT]:
            Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SIDECONTENT_RIGHT
            ?>",
            "template": "<?php echo (in_array($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_TEMPLATE],
            Unbxd_Searchcore_Helper_Constants::$AUTOSUGGEST_TEMPLATES))?
            $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_TEMPLATE]:
            Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_TEMPLATE_1COLUMN ?>",
            "theme": "<?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SKIN]?>",
            "mainTpl": <?php echo json_encode($mainTempateConf); ?>,
            "sideTpl": <?php echo json_encode($sideTemplateConf); ?>,
            "showCarts": <?php echo ($config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SHOW_CART] == "true")?"true":"false" ?>,
            "cartType": "separate",
            "onCartClick": function (obj) {
                //console.log("addtocart", this, arguments);
                return true;
            },
            "hbsHelpers": null,
            "onSimpleEnter": function(){
                //console.log("Simple enter :: do a form submit")
                this.input.form.submit();
            },
            "onItemSelect": function (data,original) {
                if (data.type == "POPULAR_PRODUCTS") {
                    if('<?php echo $productUrlField ?>' in original) {
                        window.location = original.<?php echo $productUrlField ?>;
                        return;
                    }
                }
                this.input.form.submit();
            },
            "inFields": {
                "count": 2,
                "fields": {
                    "<?php echo $brandField; ?>": 3,
                    "<?php echo $categoryField ?>": 3
                },
                "header": "<?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_SEARCH_SCOPE_HEADER]?>"
            },
            "topQueries": {
                "count": 2,
                "header": "<?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_TOPQUERY_HEADER]?>"
            },
            "keywordSuggestions": {
                "count": 2,
                "header": "<?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_KEYWORD_HEADER] ?>"
            },
            "popularProducts": {
                "count": 2,
                "price": true,
                "priceFunctionOrKey": "<?php echo $priceField ?>",
                "image": true,
                "imageUrlOrFunction": "<?php echo $imageField ?>",
                "currency": "<?php echo Mage::app()->getLocale()->currency(Mage::app()->getStore()->getCurrentCurrencyCode())->getSymbol(); ?>",
                "header": "<?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_POP_PRODUCT_HEADER] ?>"
            },
	    "maxSuggestions": <?php echo $config[Unbxd_Searchcore_Helper_Constants::AUTOSUGGEST_MAX_SUGGESTION]; ?>,
            "resultsContainerSelector": null,
            "processResultsStyles": null
        };
        jQuery(function () {
            jQuery("#search").unbxdautocomplete(config);
        });
    </script>
<?php
}
?>
